### ISSUE TITLE
Map rendering is skewed when using version of aframe above 0.3.x 

### ISSUE THREAD

**Issue by chiubaca** [jesstelford/aframe-map#7]
As the title states, when using a version of A-frame above 0.3.x the map does not render quite right and is getting skewed. Some codepens to demonstrate the issue.

v0.3.0  - map looks nice and crisp.
https://codepen.io/chiubaca/pen/NvOLMq 

v0.6.0 - map is rendering is distorted.
https://codepen.io/chiubaca/pen/EvdeEb

**Comment by mattrei** [comment]
i also ran into this thing, and you can fix it by not using <a-map> but <a-entity map="">. see my other issue below..

**Comment by mattrei** [comment]
fixed with #9
